check_batteries: True

enable_gamepad_positions: True

bedx: -5.31947212506
bedy: -0.82432398283
bedz: -0.999158054544
bedw: 0.0410266016149

pillx: -1.55760080472
pilly: 1.72284116303
pillz: -0.223404316096
pillw: 0.97472586482

chairx: -1.55760080472
chairy: 1.72284116303
chairz: -0.223404316096
chairw: 0.97472586482

walkx: -1.44441210017
walky: 2.13687967114
walkz: -0.982876826185
walkw: 0.184263790659
